# This will require each of these plugins automatically.
plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title                    : "North Coast CNPS Nursery"
name                     : "North Coast CNPS Nursery"
#baseurl                  : /northcoastcnpsnursery
include                  : ["_pages"]
#logo                     : "/assets/images/logo/leaf-icon.png"
search                   : true
