# This will require each of these plugins automatically.
plugins:
  - jekyll-include-cache
  - jekyll-paginate-v2

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title                    : "North Coast CNPS Nursery"
name                     : "North Coast CNPS Nursery"
#baseurl                  : /northcoastcnpsnursery
include                  : ["_pages"]
logo                     : "/assets/images/logo/logo.jpg"
search                   : true

paginate                 : 5 # amount of posts
paginate_path            : "/recent/page:num/"
# pagination:
#  enabled: true
#  limit: 1
#  per_page: 3
#  sort_field: 'date'
#  sort_reverse: true

collections_dir          : collections
collections:        
    plants:
        output: true
        permalink: /:collection/:name
    inventory:
        output: true
        permalink: /:collection/:name
defaults:
 - scope:
     type: "plants"
   values:
     layout: plant
     title: ""
 - scope:
     type: "inventory"
   values:
     title: ""
     layout: inventory
  # _posts
 - scope:
     path: ""
     type: posts
   values:
     layout: single
     author_profile: false
     read_time: false
     comments: # true
     share: true
     related: true
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/northcoastcnpsnursery"    
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/northcoastcnpsnursery"    
    - label: "Powered by GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kaycix/northcoastcnpsnursery"
