# This will require each of these plugins automatically.
plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title                    : "North Coast CNPS Nursery"
name                     : "North Coast CNPS Nursery"
#baseurl                  : /northcoastcnpsnursery
include                  : ["_pages"]
#logo                     : "/assets/images/logo/leaf-icon.png"
search                   : true
collections_dir          : collections
collections:        
        plants:
            output: true
            permalink: /:collection/:name
defaults:
 - scope:
     type: "plants"
   values:
     layout: plant
     title: ""
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/northcoastcnpsnursery"    
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/northcoastcnpsnursery"    
    - label: "Powered by GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kaycix/northcoastcnpsnursery"
